---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ipchangedetectors.crds.cloudflare.com
spec:
  group: crds.cloudflare.com
  names:
    kind: IPChangeDetector
    plural: ipchangedetectors
    singular: ipchangedetector
    shortNames:
    - "ipcd"
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        description: 'IPChangeDetector is the Schema for the ipchangedetector API.'
        properties:
          apiVersion:
            type: string
            description: 'APIVersion defines the versioned schema of this representation of an 
              object. Servers should convert recognized schemas to the latest internal 
              value, and may reject unrecognized values. More info: 
              https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          kind:
            type: string
            description: 'Kind is a string value representing the REST resource this object 
              represents. Servers may infer this from the endpoint the client submits 
              requests to. Cannot be updated. In CamelCase. More info: 
              https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          metadata:
            type: object
          spec:
            type: object
            description: 'IPChangeDetector monitors the NAT IP address and updates the target reference when it changes.'
            properties:
              targetRefs:
                type: array
                items:
                  type: object
                  properties:
                    apiVersion:
                      type: string
                      nullable: true
                      description: 'API version of the referent.'
                    name:
                      type: string
                      description: 'Name of the referent; More info: http://kubernetes.io/docs/user-guide/identifiers#names'
                  required:
                  - name
              interval:
                type: string
                description: 'Interval is the time interval between checks.'
            required:
            - targetRefs
            - interval
          status:
            type: object
            description: 'IPChangeDetectorStatus defines the observed state of the NAT IP address.'
